### ISSUE TITLE
[FIX] 1차 배포 후 오류 수정

### ISSUE THREAD

**Issue by AAminha** [Weflo-B/Weflo-FE#26]
## 이슈 내용

- 각종 오류를 수정합니다.
- 브랜치 이름은 `fix/#26/minha`로 할게요..! 브랜치를 따로 생성하기에는 각 수정사항이 너무 자잘함!

## To-do

- [x] 페이지 첫 진입 시, 부품 주문 count값을 가져오지 못하는 현상 수정
  - [x] 기본 path를 '/order'로 수정
  - [x] recoil를 이용해 업데이트 값을 가져오도록 수정
- [x] zoom 80%로 수정
- [x] 오타 수정
  - [x] `잡화처리` -> `집화처리`
